Schema Change
purduesigbots/pros-cli pull request #148
Opened 2021-01-29 21:13 UTC by WillXuCodes

#### Summary:
This PR attempts to future proof upload header in the case that VEX increases the schema size. Instead of NACKing when the schema is larger than the length, it will instead ask the user to upgrade PROS instead.

2021-01-29 21:14 UTC, HotelCalifornia requested changes

2021-01-29 21:14 UTC, HotelCalifornia commented on pros/serial/devices/vex/v5_device.py
> +            raise VEXCommError("Received length is less than {} (got {})".format(rx_length, len(msg)), msg)
use format string literals

2021-01-29 21:14 UTC, HotelCalifornia commented on pros/serial/devices/vex/v5_device.py
> +            ui.echo("WARNING: Recieved length is more than {} (got {}). Consider upgrading the PROS (CLI Version: {}).".format(rx_length, len(msg),get_version()))
same here

2021-01-30 07:03 UTC, WillXuCodes commented
Note: This PR does not work. Will debug soon.

2021-01-30 07:36 UTC, WillXuCodes commented
Aforementioned issue has been fixed and tested.

2021-02-18 01:08 UTC, kunwarsahni01 commented
Tested with hardware and LGTM

2021-02-18 01:09 UTC, kunwarsahni01 approved these changes

2021-02-18 01:11 UTC, HotelCalifornia approved these changes
lgtm

2021-02-18 01:13 UTC, merged