Feature/terminal file output
purduesigbots/pros-cli pull request #220
Opened 2022-07-03 00:12 UTC by sharmaneha03

#### Summary:
Added terminal option that sends output to a file by redirecting the standard output stream. Output is displayed in both the terminal and file. 

##### References (optional):
Closes #108 (Add File Redirect Option to Terminal)

#### Test Plan:
Using the command `pros terminal --output [filename]` should show output in the terminal and the selected file. Afterwards, it should return to the original state of the standard output stream (terminal only).

2022-07-15 12:54 UTC, WillXuCodes requested changes

2022-07-15 12:54 UTC, WillXuCodes commented on pros/cli/terminal.py
> +        print(f'Redirecting Terminal Output to File: {output_file}')
```suggestion
       logger(__name__).info(f'Redirecting Terminal Output to File: {output_file}')
```

2022-08-04 02:30 UTC, WillXuCodes approved these changes
For what this is, it works as intended, everything from stdout goes into a file. However, one design consideration we should consider for the future is to prevent the header and any warnings from going into the terminal if requested. However, this is easier said than done and also it might be advantageous to keep this in here anyways.

Output after running `pros terminal --output` and running a default PROS Project:
```
WARNING - pros.serial.terminal.terminal:stop - Stopping terminal
WARNING - pros.serial.terminal.terminal:stop - Stopping terminal



         [1;33m_+=+_[0m
     [1;33m .-`  .  `-. [0m         8888888b.  8888888b.   .d88888b.   .d8888b.
  [1;33m _+`     "     `+_ [0m      888   Y88b 888   Y88b d88P" "Y88b d88P  Y88b
  [1;33m\\\sssssssssssss///[0m      888    888 888    888 888     888 Y88b.
     [1;33m.ss\  [37m*[33m  /ss.[0m         888   d88P 888   d88P 888     888  "Y888b.
 [1;33m.+bm[0m  [1;33m.s[37m  *  [33ms.[0m  [1;33mmd+.[0m     8888888P"  8888888P"  888     888     "Y88b.
[1;33m.hMMMMs[0m [1;33m.[37m  *  [33m.[0m [1;33msMMMMh.[0m    888        888 T88b   888     888       "888
 [1;33m`\hMMMb[0m [1;33m\[37m | [33m/[0m [1;33mdMMMh:[0m      888        888  T88b  Y88b. .d88P Y88b  d88P
   [1;33m-SNMNo[0m  [1;33m-[0m  [1;33moNMNs-[0m       888        888   T88b  "Y88888P"   "Y8888P"
     [1;33m`+dMh\./dMd/[0m
        [1;33m`:yNy:`[0m                      [1;33mPowered by PROS for VEX V5[0m
           [1;33m"[0m                Copyright (c) Purdue University ACM SIGBots
Version:[1m3.6.3-commit.7.fa8dcc7[0m     Platform:  [1mV1.1.0 (b8)[0m     Uptime:[1m    0.000 s[0m
Compiled:   [1m             Unknown[0m     Directory:  [1m               Unknown[0m


WARNING - pros.serial.terminal.terminal:stop - Stopping terminal
```

2022-08-06 21:41 UTC, kunwarsahni01 approved these changes
After re-configuring on my end looks like it all works on macos m1.

2022-08-22 01:26 UTC, merged