✨Flags for PROS 4 Beta Templates
purduesigbots/pros-cli pull request #256
Opened 2022-12-27 20:19 UTC by omegaStag

#### Summary:
Adds a beta depot to the remote depots (currently only contains a 3.7.3 kernel template labeled as 4.0.0), adds ``--pros-4`` flags for conductor commands to use the beta depot

#### Motivation:
For PROS 4 beta testing

##### References (optional):
Contains changes made in PR #253 and PR #251 and closes their respective issues

#### Test Plan:
- [ ] Making project with ``--pros-4`` should use beta depot
- [ ] Upgrading with ``pros c upgrade --pros-4`` on a PROS 3 project should have a warning
- [ ] Downgrading with ``pros c apply-template kernel@3.x.x`` on a PROS 4 project should have a warning
- [ ] ``pros c q --pros-4`` should list beta templates too

2023-01-13 00:42 UTC, ayushuk commented
Will be revisited when the pros 4 is up on the depot. Was tested with dummy pros 3 template with adjusted metadata.

2023-01-27 04:12 UTC, WillXuCodes requested changes, later dismissed
Overall functionality is good, just needs one minor naming change.

2023-01-27 04:12 UTC, WillXuCodes commented on pros/conductor/conductor.py
> +BETA_URL = 'https://purduesigbots.github.io/pros-mainline/beta/pros-4-beta.json'
can we name this just `kernel-beta-mainline.json`? just a more futureproof name. idea is we use this for all beta testing on the kernel.

2023-02-21 02:07 UTC, omegaStag commented
progress: making pros 3 and 4 projects works. even when beta templates are cached, making a pros 3 project will make a pros 3 project. the up/downgrade warning shows up when you try and apply kernel 3 to kernel 4 project and vis versa. query-templates shows only mainline templates without the --beta flag, shows both mainline and beta with --beta. pros c upgrade will try to put your proj kernel to 4, which it will, and then errors out when it tries to upgrade any incompatible tempaltes also on the project. having a mismatched kernel 3 or 4 with a 4 or 3 compatible template will cause you to be unable to uninstall the incompatible ones until you go back to the compatible kernel version.

2023-03-03 01:40 UTC, omegaStag commented
update: added a check in project class so that if an incompatible template is already installed it will uninstall it instead of not uninstalling. this allows for pros 3 templates to be uninstalled from pros 4 projects and vis versa.

2023-04-17 21:34 UTC, kunwarsahni01 commented on pros/cli/conductor.py
> +@click.option('--no-make-clean', is_flag=True, default=False, help='Do not run make clean after removing')
```suggestion
```
Should probably not be in this PR

2023-04-17 21:35 UTC, kunwarsahni01 commented on pros/cli/terminal.py
Discard Changes

2023-04-18 00:55 UTC, kunwarsahni01 approved these changes
FIWB

2023-04-18 00:55 UTC, merged