⚡ Add V5 upload compression
purduesigbots/pros-cli pull request #48
Opened 2019-02-02 02:13 UTC by HotelCalifornia

#### Summary:

Adds a new option for uploading binaries to the V5:

```
$ prosv5 u --compress-bin
```

The default value is true (and can be switched off with `--no-compress-bin`). When compression is enabled, .bin files to be uploaded are first compressed with gzip, which is supported natively on the V5.

(there is a side change included with this PR that adds a missing letter to the name of an internally used class)

#### Motivation:

One of a series of PRs aimed at improving speed and reliability of wireless uploading.

##### References (optional):

Together with #46, this blocks #47 

#### Test Plan:

- [ ]  run prosv5 u (targeting a v5). bin/output.compressed.bin should be created, and it should have uploaded successfully
- [ ] run prosv5 u --no-compress-bin (targeting a v5). only the normal bin/output.bin should be uploaded
- [ ] run prosv5 u (targeting a cortex). nothing out of the ordinary should happen

2019-02-02 03:20 UTC, edjubuh requested changes

2019-02-02 03:20 UTC, edjubuh commented on pros/serial/devices/vex/v5_device.py
> +        if kwargs['compress_bin'] and self.status['system_version'] in Spec('>=1.0.5'):
I would prefer that compress_bin be explicity mentioned in the function signature, rather than part of kwargs because kwargs is passed straight into `ft_initialize`, which may or may not have meaning for compress_bin. It doesn't currently, but the logic we're following is "this argument is explicitly defined here (instead of in kwargs) if it's used only in this function"

2019-02-02 03:20 UTC, edjubuh commented on pros/serial/devices/vex/v5_device.py
> +        # TODO: necessary?
Probably not, but doesn't hurt to have it. Can get rid of the comment

2019-02-04 02:12 UTC, edjubuh commented
I've pushed [scratch/test-46-47-48](https://github.com/purduesigbots/pros-cli/tree/scratch/test-46-47-48) which has the 3 PRs merged together so we can test everything together.

2019-02-12 01:18 UTC, HotelCalifornia commented
Interactive UI checkbox added to the upload project modal

![](https://puu.sh/CKQIc/5177e3a53d.png)

2019-02-12 01:45 UTC, edjubuh approved these changes
![Make it so](https://i.imgur.com/YjPyGn8.png)

2019-02-12 01:49 UTC, merged